/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "irstream.pb-c.h"
void   irmessage__init
                     (IRMessage         *message)
{
  static IRMessage init_value = IRMESSAGE__INIT;
  *message = init_value;
}
size_t irmessage__get_packed_size
                     (const IRMessage *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &irmessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t irmessage__pack
                     (const IRMessage *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &irmessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t irmessage__pack_to_buffer
                     (const IRMessage *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &irmessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IRMessage *
       irmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IRMessage *)
     protobuf_c_message_unpack (&irmessage__descriptor,
                                allocator, len, data);
}
void   irmessage__free_unpacked
                     (IRMessage *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &irmessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor irmessage__field_descriptors[1] =
{
  {
    "c",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(IRMessage, n_c),
    PROTOBUF_C_OFFSETOF(IRMessage, c),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned irmessage__field_indices_by_name[] = {
  0,   /* field[0] = c */
};
static const ProtobufCIntRange irmessage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor irmessage__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "IRMessage",
  "IRMessage",
  "IRMessage",
  "",
  sizeof(IRMessage),
  1,
  irmessage__field_descriptors,
  irmessage__field_indices_by_name,
  1,  irmessage__number_ranges,
  (ProtobufCMessageInit) irmessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
