/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_irstream_2eproto__INCLUDED
#define PROTOBUF_C_irstream_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _IRMessage IRMessage;


/* --- enums --- */


/* --- messages --- */

struct  _IRMessage
{
  ProtobufCMessage base;
  size_t n_c;
  uint32_t *c;
};
#define IRMESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&irmessage__descriptor) \
    , 0,NULL }


/* IRMessage methods */
void   irmessage__init
                     (IRMessage         *message);
size_t irmessage__get_packed_size
                     (const IRMessage   *message);
size_t irmessage__pack
                     (const IRMessage   *message,
                      uint8_t             *out);
size_t irmessage__pack_to_buffer
                     (const IRMessage   *message,
                      ProtobufCBuffer     *buffer);
IRMessage *
       irmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   irmessage__free_unpacked
                     (IRMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*IRMessage_Closure)
                 (const IRMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor irmessage__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_irstream_2eproto__INCLUDED */
